# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 903fec2efab1ecde552fb0939a5056e216ecfd6561d02a6a1b5cb62029e60afe707780facb8db43fa078cd23670c7ff61e04d47aeb065f3266cd5effb6362635

test:
  secret_key_base: c4cc1f23537affadf0da48f87f8c4db332848354a636e7ca9dc55c3c44dd7d1d67ba859502a09cca37ab762542d95cb27c8715114d148b5f5e0c347fc0e614d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
